### ISSUE TITLE
Module 'glob' is missing

### ISSUE THREAD

**Issue by MikeDevice** [microsoft/license-checker-webpack-plugin#24]
If create a new project without any dependencies and try to build, the `Cannot find module 'glob'` error happens.

Steps to reproduce:
1. Create an empty project.
2. install `webpack`, `webpack-cli` and `license-checker-webpack-plugin`.
3. Create a `webpack.config.js` with the follow context:

```js
const LicenseCheckerWebpackPlugin = require("license-checker-webpack-plugin");

module.exports = {
  plugins: [new LicenseCheckerWebpackPlugin()]
};
```

4. Run `webpack` command.

**Comment by unindented** [comment]
Ugh, you're totally right. I've published `v.0.1.6` with `glob` in the list of dependencies. Sorry about that @MikeDevice!
