### ISSUE TITLE
Webpack@5 shows DeprecationWarning

### ISSUE THREAD

**Issue by MikeDevice** [microsoft/license-checker-webpack-plugin#27]
`Webpack@5` shows DeprecationWarning with the follow content:

> DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

**Comment by unindented** [comment]
Ah, that sucks. Do you know how one's supposed to emit new assets with Webpack v5?

**Comment by MikeDevice** [comment]
Not sure, but I'd like to figure out.
