### ISSUE TITLE
How can I use the output from this plugin in my source?

### ISSUE THREAD

**Issue by dminkovsky** [Microsoft/license-checker-webpack-plugin#9]
Hello! Thank you for this plugin.

I've [got a question I posted to SO](https://stackoverflow.com/questions/55436759/how-can-i-use-build-products-in-a-webpack-build) that isn't getting any traction: Copying from the question:

> 
> I am using https://github.com/Microsoft/license-checker-webpack-plugin to generate a text file containing the licenses my app uses.
> 
> I would like to load output from this plugin (a text file) with https://github.com/webpack-contrib/raw-loader to use in a page.
> 
> Unfortunately, there's a bit of a circular dependency here: this output is only available after the build. How do I handle this? Do I run webpack twice in my build?

Specifically, I am using this tool to generate https://www.pony.gg/attributions. For now, given this problem, I just copied the output from this plugin to into src. But that means every time my dependencies change I need to manually do this.

I feel like I'm missing something because isn't this a common use-case for this plugin?

**Comment by unindented** [comment]
This plugin can only produce its output at the end of Webpack's compilation, cause it needs to know all the dependencies that went into your build. Hence, you can't load that output as a dependency (e.g. using `require`), as that would need to happen during the compilation.

What you could do is publish the `ThirdPartyNotice.txt` file with your other static assets, and when your https://www.pony.gg/attributions page loads, fetch it over the network and render it.

Did that make sense?

**Comment by unindented** [comment]
In the projects I've worked on, we've just linked to the txt file directly, so we didn't have this issue.

**Comment by dminkovsky** [comment]
Hi @unindented, yep that makes sense. I had considered fetching it over the network, which will work in my webapp, but I will also be packing this with Cordova/Electron, and in those cases the built assets are referenced by "file://". I admit I haven't tried and am not totally certain, but I can't imagine that schema is accessible via XHR or some other mechanism that could break the circular dependency. Anyway, just thought I'd ask. I will link to the text file if I can't find a way to render in the app. Thank you!
